### ISSUE TITLE
Type seeder design

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1144]
- [ ] Remove `TypeSeeder` and use `SeedBaseTypesService`

---

Is this `baseTypes` solely to act as a cached data source to avoid extra db calls?

https://github.com/codelab-ai/codelab.ai/blob/1492af25a7c1919ae140236471c4b14c6cade5f6/apps/cli/src/seeder/models/type-seeder.ts#L33

We already have a base type seeder here https://github.com/codelab-ai/codelab.ai/blob/1492af25a7c1919ae140236471c4b14c6cade5f6/apps/cli/src/seeder/seeder.service.ts#L56

---

Have you noticed e2e failing for `builder-props.spec.ts`? Failing from `yarn cli seed --env test`

**Comment by antonmihaylov** [comment]
This 
https://github.com/codelab-ai/codelab.ai/blob/1492af25a7c1919ae140236471c4b14c6cade5f6/apps/cli/src/seeder/models/type-seeder.ts#L33
was created before this
https://github.com/codelab-ai/codelab.ai/blob/1492af25a7c1919ae140236471c4b14c6cade5f6/apps/cli/src/seeder/seeder.service.ts#L56

so it might be duplicated logic, at the time of writing, the TypeSeeder was responsible for seeding base types

**Comment by webberwang** [comment]
@phmngocnghia this is an old issue, not sure if it's relevant, but I'm assigning it to you because it's related to Seeder Module

**Comment by phmngocnghia** [comment]
The one in `seeder.service.ts` is used by mutation `seedBaseTypes` in admin page
![image](https://user-images.githubusercontent.com/36730355/150137265-23556c53-12ff-4ff5-9126-789b1d431d0e.png)

**Comment by phmngocnghia** [comment]
@webberwang Do you want to check builder-props spec? It has been ignore, and disabled. Story is https://github.com/codelab-ai/web/issues/1172

**Comment by webberwang** [comment]
> @webberwang Do you want to check builder-props spec? It has been ignore, and disabled. Story is #1172

Will come back to that
