### ISSUE TITLE
Sync Atoms Remotely

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1254]
- [ ] Add "SyncAtoms" in admin page & pull from remote data 

In the atoms page, we already have import atoms, this actually imports the associated type as well. So we don't need "SyncTypes" as a separate button in admin.

The import behavior also already upserts both the atoms & types. All the core logic should be there already.

This remote data will be source of truth, we will pull all atoms remotely and do an upsert locally. Any associated types will also be upserted.

## Notes
- This replaces our import/export which uses files.
- You shouldn't have to create new import/export use case, re-use the current one

**Comment by phmngocnghia** [comment]
- the same feature could be used by both external & internal dev
- [ ] Create/Set public data source by tagging
   - a checkbox when creating, and updating an app
   - for internal use, so only admin can have this input
   - This checkbox would tag an app as `public`
- [ ] Let’s implement them for internal first:
  - Have a button on the Admin page that is called: “Sync data from data sources”
  - Click on would call the API
  - API gets the data from the configured endpoint (point to staging) and import the data to the environment of the user
