### ISSUE TITLE
Create Form inside next.js page

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1262]
This is for internal use mostly. This creates a form from interface, such as our props form in builder.

Create a nextjs page `apps/web/pages/demo/form`, and use the same form component we use for the props form. This will connect to our interface data

We'll use this as a temporary place before migrating to storybook.

We'll test a list of form fields, below come up with a list of fields we should support.

On submit it should console log the data

- [ ] monoca fields
- [ ] array types
- [ ] object types
- [ ] xxx
- [ ] xxx
- [ ] xxx

**Comment by phmngocnghia** [comment]
@rihnoo I have a WIP PR on https://github.com/codelab-ai/web/pull/1272 that contains partial working code. I think that would useful for you. I have scaffolded stub data for most of our data types. I just found that I have been unassigned from story, decided to push some working code that I previously worked on my local

**Comment by rihnoo** [comment]
Ok noted. thank you @phmngocnghia

**Comment by rihnoo** [comment]
@webberwang 
I've done this issue. 
There was the [PR](https://github.com/codelab-ai/web/pull/1272) that @phmngocnghia  raised so I just edited it.

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/18/22 - 01/21/22
Work session total: 13:37:44
Billable: Yes

Grand total: 13:37:44
