### ISSUE TITLE
Create Menu Links to Pages

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1271]
Check out one of our old issues https://github.com/codelab-ai/codelab.ai/issues/1006, feature was added here https://github.com/codelab-ai/codelab.ai/pull/1107

Let's test it to make sure it's working still

**Comment by harryjin** [comment]
I checked the issues on current codebase. but it's not working as i think. in hook, data binding is not working. I upload video in slack.

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/14/22 - 01/18/22
Work session total: 7:14:25
Billable: Yes

Grand total: 7:14:25

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/18/22 - 01/18/22
Work session total: 0:33:05
Billable: Yes

Grand total: 7:47:30
