### ISSUE TITLE
Fix atom import specs

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1306]
1. remove `node_modules/nx/.cache`
2. `nx test atom --skip-nx-cache --runInBand` to see error locally

![image](https://user-images.githubusercontent.com/26264925/150615094-438f1a31-ff26-4cd3-b0eb-fa71fabc9a39.png)

need to add description to the query
then run yarn codegen to regenerated the Gql
try testing locally first before pushing
also .toMatchObject seems to work only for top level objects, not nested (edited) 
so you need to do nested expect’s using arrayContaining

**Comment by harryjin** [comment]
via Hubstaff
User: Harry Jin

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/22/22 - 01/22/22
Work session total: 2:16:19
Billable: Yes

Grand total: 2:16:19
