### ISSUE TITLE
Builder add child error

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1312]
- [ ] Restore builder e2e specs

We have ignored the builder spec, but let's revert it because of the bug we have found

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/23/22 - 01/26/22
Work session total: 13:49:40
Billable: Yes

Grand total: 13:49:40
