### ISSUE TITLE
Element instanceOfComponent

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1318]
`atom` & `instanceOfComponent` are both properties telling us what type of Element it is. We should compile both into an Element.type property, that could have reference to either an Atom or a Component.

**Comment by antonmihaylov** [comment]
I think that's a good idea, similar to how React's API works

**Comment by assimhabeek** [comment]
we could use type union offered by neo4j [here](https://neo4j.com/docs/graphql-manual/current/type-definitions/unions/)

**Comment by antonmihaylov** [comment]
I worked with unions and interfaces when implementing our Type module and it is not a first-class experience in neo4j-graphql. at least for now. There are various bugs and workarounds

**Comment by webberwang** [comment]
Ended up migrating to component model
