### ISSUE TITLE
Enable e2e specs for builder

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1359]
We had enabled this before

- Issues before we disabled
https://github.com/codelab-ai/web/issues/1172

<img width="651" alt="Mouse_Highlight_Overlay_and_ExecuteCommandModal_tsx_—_web" src="https://user-images.githubusercontent.com/26264925/151490909-efa716b4-276a-48e6-8a3c-eaafda3fdf58.png">

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/29/22 - 02/02/22
Work session total: 7:38:51
Billable: Yes

Grand total: 7:38:51
