### ISSUE TITLE
Investigate Enum Field error

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1360]
See why this error occurs

![image](https://user-images.githubusercontent.com/26264925/151492970-25b44e3c-ce7f-4837-92bc-6abf7b2d2901.png)

**Comment by rihnoo** [comment]
Hi @webberwang 

This issue has now been resolved by this [PR](https://github.com/codelab-ai/web/pull/1336).
[Video Link](https://www.loom.com/share/6c5b1391ffa64c87a5fe06312787be8e)

I think we can close this issue.

**Comment by webberwang** [comment]
Closed by #1336

**Comment by rihnoo** [comment]
via Hubstaff
User: Ming Lee

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 01/28/22 - 01/29/22
Work session total: 3:24:15
Billable: Yes

Grand total: 3:24:15
