### ISSUE TITLE
Create a place to add shared providers/components

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1398]
Currently, a user can build an app & add pages, but they don't have a central place to add shared react components (like providers).

If they wanted to integrate Auth0, they would need to add something like this to _app.tsx

![image](https://user-images.githubusercontent.com/26264925/153372111-bbae9cbe-56a1-4548-9827-392154e962c5.png)

---

We'll want to come up with a system so a dev using our platform can have a place to add shared providers. 

- [x] Give an architectural overview of how to design this system (no coding yet)
- [ ] coding

**Comment by phmngocnghia** [comment]
A page uses Providers P
Providers P includes Provider p1,p2,p3
Pattern: There's always a default list of Providers to add to each page
### Expose
* Expose Providers for user to use
  - providers are implemented by us
  - auth0 - UserProvider
  - localization - for i18n
###  Set default Provider: _app.tsx
Create a default Providers component: P
Config App A to use default Providers P
Any pages are created of app A will have app P as a wrapper by default
