### ISSUE TITLE
Migrate Type to Neo4j

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-ai/web#1417]
Implementation plan:

1. Neo4j supports multigraphs, so we can have multiple edges between the same types. This allows us to keep the fields as simply edges between nodes without the limitation of using a type only once in all the fields of an interface.
The fields would not be a separate entity, but a [@relationshipProperties declaration](https://neo4j.com/docs/graphql-manual/current/type-definitions/basics/#_relationship_properties)
2. [Graphql Interfaces](https://neo4j.com/docs/graphql-manual/current/type-definitions/interfaces/) seem appropriate - we can have a BaseType interface which each specific type will inherit. 
3. The BaseType interface would have a `graph` custom property with @cypher directive that will fetch the graph for this type.
4. PrimitiveTypes should be unique by kind - [@ unique](https://neo4j.com/docs/graphql-manual/current/type-definitions/indexes-and-constraints/#_unique_directive_usage) should do the job
5. typeKind becomes a bit pointless since we can use the __typename as source of truth. But since it's used everywhere across the codebase we can keep it and set it using @ default to the specific type kind in each specific type. Or I'll see if we can just query __typename as typeKind, that would be best of both worlds
6. Need to make sure each interface has unique keys. This could be useful https://blog.grandstack.io/authorization-in-graphql-using-custom-schema-directives-eafa6f5b4658

- [x] All use cases except import/export done in #1438 
- [ ] Import/export types

**Comment by webberwang** [comment]
So we're changing from
<img width="832" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/26264925/152351902-621994cf-e98a-4f4a-9529-32840fc71de6.png">
 
to

<img width="744" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/26264925/152352934-de5a29e4-3ef3-4d16-a7aa-5984f58e6adc.png">

?

**Comment by antonmihaylov** [comment]
That's the idea, yes. The motivation is that it would be uniform, because we use edges for UnionType -> child types and ArrayType -> array Item type
