### ISSUE TITLE
Migrate admin to MobX

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1513]
Follow app and migrate admin to use MobX keystone instead of Redux for the following use cases

- [x] export
- [x] import
- [x] reset-data

**Comment by scientiststwin** [comment]
via Hubstaff
User: Ilia Gurgenidze

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 03/28/22 - 03/30/22
Work session total: 7:04:33
Billable: Yes

Grand total: 7:04:33

**Comment by scientiststwin** [comment]
via Hubstaff
User: Ilia Gurgenidze

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 03/30/22 - 03/30/22
Work session total: 0:26:57
Billable: Yes

Grand total: 7:31:30
