### ISSUE TITLE
UI Refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1525]
- The left most sidebar should be actual tabs, and not links to new pages. This makes it a smoother experience. Also the builder main area should be visible at all times, so we would have to move some of our tables for displaying data.

# UI Strategy

Much of our data follows a tree data structure, such as elements on our page, pages/sub pages, our model hierarchy, our interfaces etc.

We'll use a tree view to show the preview of such data. On hover, there will be an edit & delete button, both of which will trigger a popover form (instead of a modal).

## Page

1. Show all pages, then have a filter on which pages to show (could show 1 or more at a time)

![image](https://user-images.githubusercontent.com/26264925/161680118-f4f225f5-2bdf-460b-af38-0a50a6f0fa26.png)

2. Show single page at a time, then have a select dropdown to select the active page

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/161680441-ebf9c645-ca60-41fb-a937-7c1d7e42d186.jpg)

3. Have the top section for showing a list of pages, then whichever is selected will show the respective DOM tree in the bottom section.

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/161680291-c16c5d25-8516-4b6d-8a7c-ef35a167be6a.jpg)
 
## Model

- On the left pane, we will display a tree list of models
- The model can open up and will contain children of either properties or methods

![Demo_-_Builder___UI_Bakery](https://user-images.githubusercontent.com/26264925/161681125-529734d6-8c19-43b9-96a7-2d2bc5e354cc.jpg)

- Clicking on the properties will open a popover form next to it for editing

![image](https://user-images.githubusercontent.com/26264925/161682677-a54f21eb-3800-44dc-bb67-192986c17e5d.png)

- Same with the actions

## Component

- This would actually be it's own page
- Instead of builder view for the page, we'll have a builder view for the components itself
- Can think of as a Storybook view

## Builder

- The right most panel would be reserved styles when clicking on an element
- The bottom most would be for showing props & bindings

## Resource & Query

I think this page can omit the builder view, as this can be worked on independently of the UI. It's for fetching API data. UIBakery seems to do this.

![image](https://user-images.githubusercontent.com/26264925/161683238-c43aa1aa-be2b-4e0c-be98-aff68dc49490.png)

**Comment by scientiststwin** [comment]
@webberwang, in my opinion, the first case is the better than other since the user can compare pages with each other, 

- [ ]
