### ISSUE TITLE
Add Tag field to Atom

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/web#1531]
Add a tag field for assigning tags to atoms, it should be a select dropdown with list of all tags

https://ant.design/components/select/#components-select-demo-multiple

**Comment by scientiststwin** [comment]
via Hubstaff
User: Ilia Gurgenidze

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 04/08/22 - 04/10/22
Work session total: 6:18:19
Billable: Yes

Grand total: 6:18:19

**Comment by scientiststwin** [comment]
via Hubstaff
User: Ilia Gurgenidze

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 04/10/22 - 04/10/22
Work session total: 0:00:07
Billable: Yes

Grand total: 6:18:26
